name: Android CI

on:
  push:
    branches:
      - main
      - yeonji
      - yiheng
      - kyriaki
      - rohit
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Generate code coverage report
        run: ./gradlew koverXmlReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/reports/kover/report.xml

      - name: List APK folder contents
        run: ls -R app/build/outputs/apk/debug/

      - name: Debug APK existence
        run: |
          echo "Checking for APK..."
          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
            echo "APK found!"
          else
            echo "APK NOT found!"
            exit 1
          fi

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4 # upgrade from v3 -> v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
